[package]
name = "biter"
version = "0.0.0"
edition = "2021"
description = "BitTorrent client written in Rust"

[dependencies]
rand = "0.8.5"
reqwest = { version = "0.11", features=["blocking"] }
sha1 = "0.10.6"
urlencoding = "2.1.3"
